### ISSUE TITLE
Storybook,  can not view component inside browser.

### ISSUE THREAD

**Issue by ducpt2** [syl20lego/rn-skeleton#2]
I trying to using your skeleton to learning, but why i try to using storybook, my browser can not see any of components in project? 
Can you know why? Thanks.

**Comment by syl20lego** [comment]
I’ll take a look when I’m back from the office, in the meantime can you
tell me which versions you are using?

thanks

**Comment by syl20lego** [comment]
I think I got it make sure you have launch the application.

react-native run-ios or react-native run-android

You need to see the storybook screen on the simulator for it to to be able to interact with the browser. 
You won't see the component in the browser, they will appear in the simulator, you use the browser to navigate/select the component you want to see in the simulator.

**Comment by ducpt2** [comment]
ok i understand, so component is only show on simulator.
Can you tell me advance when developer using storybook please? It very helpful, this tool seem like very cool.
Thanks in advance.

**Comment by syl20lego** [comment]
Hi Pham,

I'm not sure I understand the last question but will try to answer it. I personally use storybook for 3 main reasons. 
1) Quick way to get to creating your views, you don't need to setup your logic and your store and can work on the component right away. This is very useful when you work on a component that is deep inside your app.
2) it ensure that your presentation components are just that and are decouple from business logic (see https://www.fullstackreact.com/p/using-presentational-and-container-components-with-redux/) it helps to keep your components simple and storybook is also a good way to document how the component can be used. 
3) I usually don't like investing in UX automation testing, it is usually costly and hard to keep them up to date. Storybook is a way to ensure the UX is looking good and can be reviewed by the UX designer without too much knowledge about the app.

You can also see the storybook official documentation or visit the github https://github.com/storybooks/storybook/tree/master/app/react-native

Thanks for using my framework, it is very nice to see that it can help others.

If there is nothing else, I would let you close the issue.

Thanks
Sylvain

**Comment by ducpt2** [comment]
@syl20lego your answer is what i need. Thank you so much.
